//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnPTemplateManager.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BA_MetadataDefinition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BA_MetadataDefinition()
        {
            this.BA_Metadata = new HashSet<BA_Metadata>();
            this.BA_SiteTypeMetadataDefinitions = new HashSet<BA_SiteTypeMetadataDefinitions>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Definition { get; set; }
        public string Type { get; set; }
        public bool Required { get; set; }
        public Nullable<int> Instance_Id { get; set; }
        public bool HideOnDisplayForm { get; set; }
        public bool HideOnNewForm { get; set; }
        public bool HideOnEditForm { get; set; }
    
        public virtual BA_Instance BA_Instance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BA_Metadata> BA_Metadata { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BA_SiteTypeMetadataDefinitions> BA_SiteTypeMetadataDefinitions { get; set; }
    }
}
