//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnPTemplateManager.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BA_Metadata
    {
        public int Id { get; set; }
        public string Value { get; set; }
        public Nullable<decimal> ValueDecimal { get; set; }
        public int MetadataDefinition_Id { get; set; }
        public int Site_Id { get; set; }
        public Nullable<System.DateTimeOffset> ValueDate { get; set; }
    
        public virtual BA_MetadataDefinition BA_MetadataDefinition { get; set; }
        public virtual BA_Site BA_Site { get; set; }
    }
}
