//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnPTemplateManager.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BA_Phase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BA_Phase()
        {
            this.BA_Phase1 = new HashSet<BA_Phase>();
            this.BA_Site = new HashSet<BA_Site>();
            this.BA_Action = new HashSet<BA_Action>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int SiteTypeId { get; set; }
        public Nullable<int> BA_PhaseBA_Phase_BA_Phase1_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BA_Phase> BA_Phase1 { get; set; }
        public virtual BA_Phase BA_Phase2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BA_Site> BA_Site { get; set; }
        public virtual BA_SiteType BA_SiteType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BA_Action> BA_Action { get; set; }
    }
}
