//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnPTemplateManager.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BA_Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BA_Role()
        {
            this.BA_SiteRole = new HashSet<BA_SiteRole>();
            this.BA_Principal = new HashSet<BA_Principal>();
        }
    
        public int RepositoryConfigRoleId { get; set; }
        public string Name { get; set; }
        public long PermissionMask { get; set; }
        public bool AllowMultiple { get; set; }
        public bool AllowPersons { get; set; }
        public bool AllowGroups { get; set; }
        public bool CanEditMetadata { get; set; }
        public bool CanAssignRoles { get; set; }
        public int SortOrder { get; set; }
        public int SiteType_Id { get; set; }
        public bool CanReadNoticeboard { get; set; }
        public bool CanWriteNoticeboard { get; set; }
        public bool AddCurrentUserInNewForm { get; set; }
        public bool CanBeDeleted { get; set; }
        public bool CanBeModified { get; set; }
        public string InternalName { get; set; }
        public Nullable<int> Instance_id { get; set; }
        public bool HideOnDisplayForm { get; set; }
        public bool HideOnNewForm { get; set; }
        public bool HideOnEditForm { get; set; }
        public bool CanAddToOwnRole { get; set; }
        public bool CanRemoveFromOwnRole { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BA_SiteRole> BA_SiteRole { get; set; }
        public virtual BA_SiteType BA_SiteType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BA_Principal> BA_Principal { get; set; }
    }
}
