//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnPTemplateManager.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BA_Site
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BA_Site()
        {
            this.BA_Metadata = new HashSet<BA_Metadata>();
            this.BA_SiteHistory = new HashSet<BA_SiteHistory>();
            this.BA_SiteRole = new HashSet<BA_SiteRole>();
            this.BA_Principal1 = new HashSet<BA_Principal>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public System.Guid SharePointWebId { get; set; }
        public int Status { get; set; }
        public System.DateTime StatusLastChanged { get; set; }
        public int SiteType_Id { get; set; }
        public int CurrentPhase_Id { get; set; }
        public int StatusLastChangedBy_PrincipalId { get; set; }
        public string PropertyBag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BA_Metadata> BA_Metadata { get; set; }
        public virtual BA_Phase BA_Phase { get; set; }
        public virtual BA_Principal BA_Principal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BA_SiteHistory> BA_SiteHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BA_SiteRole> BA_SiteRole { get; set; }
        public virtual BA_SiteType BA_SiteType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BA_Principal> BA_Principal1 { get; set; }
    }
}
