//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnPTemplateManager.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BA_SiteRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BA_SiteRole()
        {
            this.BA_SiteRolePrincipals = new HashSet<BA_SiteRolePrincipals>();
        }
    
        public int Id { get; set; }
        public int Site_Id { get; set; }
        public int Role_RepositoryConfigRoleId { get; set; }
    
        public virtual BA_Role BA_Role { get; set; }
        public virtual BA_Site BA_Site { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BA_SiteRolePrincipals> BA_SiteRolePrincipals { get; set; }
    }
}
