//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnPTemplateManager.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BA_SiteRolePrincipals
    {
        public System.DateTime Created { get; set; }
        public int BA_SiteRoleId { get; set; }
        public int BA_PrincipalPrincipalId { get; set; }
        public int CreatedBy_PrincipalId { get; set; }
    
        public virtual BA_Principal BA_Principal { get; set; }
        public virtual BA_Principal BA_Principal1 { get; set; }
        public virtual BA_SiteRole BA_SiteRole { get; set; }
    }
}
