//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PnPTemplateManager.BLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Wizdom365X2Entities : DbContext
    {
        public Wizdom365X2Entities()
            : base("name=Wizdom365X2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BA_Action> BA_Action { get; set; }
        public virtual DbSet<BA_App> BA_App { get; set; }
        public virtual DbSet<BA_Instance> BA_Instance { get; set; }
        public virtual DbSet<BA_Metadata> BA_Metadata { get; set; }
        public virtual DbSet<BA_MetadataDefinition> BA_MetadataDefinition { get; set; }
        public virtual DbSet<BA_Phase> BA_Phase { get; set; }
        public virtual DbSet<BA_Principal> BA_Principal { get; set; }
        public virtual DbSet<BA_Role> BA_Role { get; set; }
        public virtual DbSet<BA_Site> BA_Site { get; set; }
        public virtual DbSet<BA_SiteHistory> BA_SiteHistory { get; set; }
        public virtual DbSet<BA_SiteRole> BA_SiteRole { get; set; }
        public virtual DbSet<BA_SiteRolePrincipals> BA_SiteRolePrincipals { get; set; }
        public virtual DbSet<BA_SiteType> BA_SiteType { get; set; }
        public virtual DbSet<BA_SiteTypeMetadataDefinitions> BA_SiteTypeMetadataDefinitions { get; set; }
    }
}
